src/models/item.py
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Any


@dataclass(unsafe_hash=True)
class Item:
    title: str
    link: str
    price: str
    image: str
    id_: str
    tracking: bool = field(default=False)

    @staticmethod
    def from_database_columns(columns: tuple) -> Item:
        item_id = columns[0]
        return Item(
            str(columns[1]),
            str(columns[2]),
            "",
            str(columns[3]),
            item_id,
        )

    @staticmethod
    def from_dict(d: dict[str, Any]) -> Item:
        return Item(
            title=d["title"],
            link=d["link"],
            price=d["price"],
            image=d["image"],
            id_=d["id_"],
            tracking=d["tracking"],
        )

controllers/base.py
from configparser import ConfigParser
from aioflask import Flask
from flask_session import Session

app = Flask(__name__, template_folder="../templates", static_folder="../static")

ini_file = ConfigParser()
ini_file.read("config/pages.ini")
key = ini_file.get("pages", "key")

app = Flask(__name__, template_folder="../templates", static_folder="../static")
app.secret_key = b'_5#y2L"F4Q8z\n\xec]/'
app.config["SESSION_TYPE"] = "filesystem"
sess = Session(app)

controllers/mine.py
from . import _get_current_user
from aioflask import session
from flask import make_response, render_template, Blueprint
from utils.item_dao import ItemDAO

mine_blueprint = Blueprint("mine_blueprint", __name__)


@mine_blueprint.route("/mine")
def mine():
    current_user = _get_current_user(session)
    if current_user is None:
        return "broken"
    results = ItemDAO.get_tracked_items_by_user(current_user.id_)
    return make_response(
        render_template(
            "mine.html", links=results, entry_count=len(results), user=current_user
        )
    )

src/controllers/mine.py
from . import _get_current_user
from aioflask import session
from flask import make_response, jsonify, Blueprint
from flask_api import status
from flask.wrappers import Response
from utils.database.item_dao import ItemDAO

mine_blueprint = Blueprint("mine_blueprint", __name__)


@mine_blueprint.route("/api/mine", methods=["GET"])
def mine() -> Response:
    session["last_page"] = "/mine"
    current_user = _get_current_user(session)
    if current_user.id_ == -1:
        return make_response(
            jsonify({"reason": "not logged in"}), status.HTTP_401_UNAUTHORIZED
        )

    results = ItemDAO.get_tracked_items_by_user(current_user.id_)
    return make_response(jsonify({"data": results}))

src/views/item_view.py
import json

from controllers.item_page import item
from flask import Blueprint, make_response, render_template
from flask.wrappers import Response
from models.user import User

item_page_view_blueprint = Blueprint("item_page_view_blueprint", __name__)


@item_page_view_blueprint.route("/item")
def item_page() -> Response:
    response = item()

    json_response = json.loads(response.data)
    try:
        data = json_response["data"]
        user = User.from_dict(json_response["user"])
        image = json_response["image"]

        return make_response(
            render_template("item.html", user=user, links=data, image=image)
        )
    except KeyError:
        return make_response(
            render_template("item.html", user=User.from_dict(json_response))
        )

src/views/login_view.py
import json
from aioflask import session
from flask import Blueprint, render_template, make_response, redirect
from flask.wrappers import Response
from models.user import User

from utils.argument_parser import *
from views.login_inner import login_inner

user_login_view_blueprint = Blueprint("user_login_view_blueprint", __name__)


@user_login_view_blueprint.route("/login", methods=["GET", "POST"])
def user_login() -> Response:
    response = json.loads(login_inner().data)

    if "reason" in response:
        actual_reason = User.Status.from_string(response["reason"])
        return make_response(render_template("login.html", reason=actual_reason))

    if not "user_id" in session or session["user_id"] == -1:
        return make_response(render_template("login.html", reason=None))
    return make_response(redirect(session["last_page"]))

src/views/logout_view.py
from aioflask import session
from flask import Blueprint, redirect, make_response
from flask.wrappers import Response
from controllers.user_logout import logout

from utils.argument_parser import *

user_logout_view_blueprint = Blueprint("user_logout_view_blueprint", __name__)


@user_logout_view_blueprint.route("/logout", methods=["POST"])
def user_logout() -> Response:
    logout()
    return make_response(redirect(session["last_page"]))

src/views/mine_view.py
import json
from aioflask import session
from flask import make_response, render_template, Blueprint
from controllers.mine import mine
from flask.wrappers import Response
from controllers import _get_current_user
from models.item import Item

mine_view_blueprint = Blueprint("mine_view_blueprint", __name__)


@mine_view_blueprint.route("/mine")
def mine_page() -> Response:
    response = mine()
    json_response = json.loads(response.data)
    try:
        data = json_response["data"]
        items = {Item.from_dict(item) for item in data}
        current_user = _get_current_user(session)
        return make_response(
            render_template(
                "mine.html", links=items, entry_count=len(items), user=current_user
            )
        )
    except KeyError:
        return make_response(
            render_template("mine.html", user=_get_current_user(session))
        )

src/views/register_view.py
import json
from aioflask import session
from flask import Blueprint, redirect, make_response, render_template
from flask.wrappers import Response

from utils.argument_parser import *
from views.register_inner import register_inner

user_register_view_blueprint = Blueprint("user_register_view_blueprint", __name__)


@user_register_view_blueprint.route("/register", methods=["GET", "POST"])
def user_register() -> Response:
    response = json.loads(register_inner().data)

    if "reason" in response:
        if response["reason"] == "user already exists":
            return make_response(render_template("register.html", reason="That user already exists"))
        if response["reason"] == "passwords are not the same":
            return make_response(render_template("register.html", reason="Passwords are not the same"))

    if not "user_id" in session or session["user_id"] == -1:
        return make_response(render_template("register.html", reason=None))
    return make_response(redirect(session["last_page"]))

src/views/track_item_view.py
from aioflask import session
from flask import Blueprint, make_response, redirect
from flask.wrappers import Response
from controllers.track_items import track_item

from utils.argument_parser import *


track_item_view_blueprint = Blueprint("track_item_view_blueprint", __name__)


@track_item_view_blueprint.route("/track", methods=["GET", "POST"])
async def track() -> Response:
    track_item()
    return make_response(redirect(session["last_page"]))

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/style.css') }}">
    <link rel="icon" type="image/x-icon" href="{{ url_for('static', filename='images/logo.svg') }}">

    <title>{% block title %}{% endblock %}</title>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous" defer>
    </script>
    <script src="{{ url_for('static', filename='scripts/index.js') }}" type="module" defer></script>
    <script src="{{ url_for('static', filename='scripts/url.js') }}" type="module" defer></script>
    <script src="{{ url_for('static', filename='scripts/login.js') }}" defer></script>
</head>

<body>
    <header>
        <div class="navbar">
            <a href="/">
                <img src="{{ url_for('static', filename='images/logo.svg') }}" alt="logo" width="50px">
            </a>
            <form action="/" method="get">
                <div>
                    <input type="text" name="q" id="user-prompt" placeholder="search...">
                    <div id="advanced-button" class="fake-button">Show advanced</div>
                    <button type="submit" class="fake-button">Search</button>
                </div>
                <div id="advanced-search-options">
                    <label for="search-count">Results:</label>
                    <input type="number" name="search-count" id="search-count">
                    <div id="price-min-value">
                        <label for="price-min">Minimum price:</label>
                        <input type="range" min="0" max="9999" name="price-min" id="price-min">
                        <div id="price-min-number">-</div>
                    </div>
                    <div id="price-max-value">
                        <label for="price-max">Maximum price:</label>
                        <input type="range" min="0" max="9999" name="price-max" id="price-max">
                        <div id="price-max-number">-</div>
                    </div>
                    {% if user and user.ok and user.can_refresh %}
                    <div>
                        <label for="refresh-items">Refresh search</label>
                        <input type="checkbox" name="refresh-items" id="refresh-items">
                    </div>
                    {% endif %}
                </div>
            </form>
            <div>
                <a href="{{ url_for('mine_view_blueprint.mine_page') }}" class="link fake-button">My tracked items</a>
            </div>
            <div class="user-details">{% if user and user.ok %}
                <div>
                    <p>
                        Welcome, {{ user.name }}
                    </p>
                    <form action="{{ url_for('user_logout_view_blueprint.user_logout') }}" method="post">
                        <input type="submit" value="Logout">
                    </form>
                </div>
                {% else %}
                <div>
                    <a href="{{ url_for('user_login_view_blueprint.user_login') }}">Login</a>
                    <a href="{{ url_for('user_register_view_blueprint.user_register') }}">Register</a>
                </div>
                {% endif %}
            </div>
        </div>
    </header>
    {% block content %} {% endblock %}
    <footer>
        Made with &#9829; by Radu-Alexandru Popa and Radu Sofron
    </footer>{% block scripts %} {% endblock %}
</body>

</html>

templates/index.html
{% extends "base.html" %} {% block title %} Main page {% endblock %} {% block scripts %} {% endblock %} {% block content %}

<div class="main">
    <h1>YOUR NAME: {{ gettext("Computer") }} </h1>
    <h1>anthony: {{ anthony }} </h1>
    {% if links %}
    <p>Found {{ entry_count }} entries</p>
    <table class="table table-borderless table-responsive my-table">
        <thead>
            <tr>
                <th>Image</th>
                <th>Product name</th>
                <th>Price</th>
                <th>Tracking</th>
            </tr>
        </thead>
        {% for item in links %}
        <tr>
            <td>
                <a href="/item/{{ item.id_ }}">
                    <img src="{{ item.image }}" alt="product image" class="img-fluid" width="20%">
                </a>
            </td>
            <td>
                <a href="{{ item.link }}"> {{ item.title }} </a>
            </td>
            <td>
                {{ item.price }}
            </td>
            <td>
                <form action="{{ url_for('track_item_view_blueprint.track') }}" method="post">
                    {% if item.tracking %}
                    <input type="image" src="{{ url_for('static', filename='images/checkbox_on.svg') }}" alt="tracking" name="unset{{ item.id_ }}" id="item{{ item.id_ }}"> {% else %}
                    <input type="image" src="{{ url_for('static', filename='images/checkbox_off.svg') }}" alt="not tracking" name="set{{ item.id_ }}" id="item{{ item.id_ }}"> {% endif %}
                </form>
            </td>
        </tr>
        {% endfor %}
    </table>
    {% endif %}
</div>
{% endblock %}

templates/item.html
{% extends "base.html" %} {% block title %} Item {% endblock %} {% block content %}
<div class="main">
    <div class="inner">
        <div class="side"><img src="{{ image }}" alt=""></div>
        <div class="prices">
            <div class="graph">
                {% for item in links %} {% set raw_price_string = item["price"].split(' Lei')[0].replace(',', '.') %} {% set raw_price = (raw_price_string|int)*100//100 %}
                <div class="graph-bar" style="height: {{ raw_price * 10 }}px;">
                    <p>
                        {{ item["price"] }}
                    </p>
                    <p>
                        {{ item["date"][:10] }}
                    </p>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/login.html
{% extends "base.html" %} {% block title %} Main page {% endblock %} {% block scripts %} {% endblock %} {% block content %}
<div class="center login">
    <form action="{{ url_for('user_login_view_blueprint.user_login') }}" method="post">
        <div class="formdiv">
            <label for="user-name">Name</label>
            <input type="text" name="user-name" id="user-name" required>
        </div>
        <div class="formdiv">
            <label for="user-password">Password</label>
            <input type="password" name="user-password" id="user-password" required>
        </div>
        <input type="submit" style="display: none;">
    </form>
    {% if reason %} {{ reason }} {% if reason.value == 4 %}
    <div>
        Forgot your password? Click <a href="/">here</a>
    </div>
    {% endif %}{% endif %}
    <div>
        No account? Register
        <a href="{{ url_for('user_register_view_blueprint.user_register') }}">here</a> first
    </div>
</div>
{% endblock %}

templates/mine.html
{% extends "base.html" %} {% block title %} My trackings {% endblock %} {% block content %}
<div class="main">
    {% if user.ok %} {% if links %}
    <p>Found {{ entry_count }} entries</p>
    <p>My trackings:</p>
    <table class="table table-borderless table-responsive my-table">
        <thead>
            <tr>
                <th>Image</th>
                <th>Product name</th>
                <th>Price</th>
                <th>Tracking</th>
            </tr>
        </thead>
        {% for item in links %}
        <tr>
            <td>
                <a href="/item?id={{ item.id_ }}">
                    <img src="{{ item.image }}" alt="product image" class="img-fluid" width="20%">
                </a>
            </td>
            <td>
                <a href="{{ item.link }}"> {{ item.title }} </a>
            </td>
            <td>
                {{ item.price }}
            </td>
            <td>
                <form action="{{ url_for('track_item_view_blueprint.track') }}" method="post">
                    <input type="image" src="{{ url_for('static', filename='images/checkbox_on.svg') }}" alt="tracking" name="unset{{ item.id_ }}" id="item{{ item.id_ }}">
                </form>
            </td>
        </tr>
        {% endfor %}
    </table>
    {% else %}
    <p>Click on the checkbox next to an item to add it here</p>
    {% endif %} {% else %}
    <p>Log in first to see your tracked items</p>
    {% endif %}
</div>
{% endblock %}

templates/register.html
{% extends "base.html" %} {% block title %} Registration {% endblock %} {% block scripts %} {% endblock %} {% block content %}
<div class="center login">
    <form action="{{ url_for('user_register_view_blueprint.user_register') }}" method="post">
        <div class="formdiv">
            <label for="user-name">Name</label>
            <input type="text" name="user-name" id="user-name" required>
        </div class="formdiv">
        <div>
            <label for="user-password">Password</label>
            <input type="password" name="user-password" id="user-password" required>
        </div>
        <div class="formdiv">
            <label for="user-password">Confirm password</label>
            <input type="password" name="user-password-confirm" id="user-password-confirm" required>
        </div>
        <input type="submit" style="display: none;">
    </form>
    {% if reason %} {{ reason }} {% endif %}
    <div>
        Already have an account? Log in
        <a href="{{ url_for('user_login_view_blueprint.user_login') }}">here</a>
    </div>
</div>
{% endblock %}